package Component;

import Client.User_Account;
import java.awt.Color;

public class ChatTitle extends javax.swing.JPanel {

    public User_Account getUser() {
        return user;
    }

    private User_Account user;

    
    public ChatTitle() {
        initComponents();
    }

    public void setUserName(User_Account user) {
        this.user = user;
        lbName.setText(user.getUsername());
        if (user.isStatus()) {
            statusActive();
        } else {
            setStatusText("Offline");
        }
    }
    
    public void updateUser(User_Account user) {
        if (this.user == user) {
            lbName.setText(user.getUsername());
            if (user.isStatus()) {
                statusActive();
            } else {
                setStatusText("Offline");
            }
        }
    }
    
    public void statusActive() {
        lbStatus.setText("Active now");
        lbStatus.setForeground(new Color(22,170,47));
    }
    
    private void setStatusText(String text) {
        lbStatus.setText(text);
        lbStatus.setForeground(new Color(160, 160, 160));
    }
    
    public void setStatus(String text) {
        lbStatus.setText(text);
        lbStatus.setForeground(new Color(107, 107, 107));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        layer = new javax.swing.JLayeredPane();
        lbName = new javax.swing.JLabel();
        lbStatus = new javax.swing.JLabel();

        setBackground(new java.awt.Color(213, 229, 232));

        layer.setLayout(new java.awt.GridLayout(0, 1));

        lbName.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        lbName.setText("Name");
        layer.add(lbName);

        lbStatus.setFont(new java.awt.Font("Cambria", 2, 10)); // NOI18N
        lbStatus.setForeground(new java.awt.Color(22, 170, 47));
        lbStatus.setText("Active now");
        layer.add(lbStatus);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(layer, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(211, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(layer)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane layer;
    private static javax.swing.JLabel lbName;
    private static javax.swing.JLabel lbStatus;
    // End of variables declaration//GEN-END:variables
}
