package Component;

import java.awt.Color;
import java.util.Date;
import javax.swing.Icon;

/**
 *
 * @author HOAI THU
 */
public class ChatLeft extends javax.swing.JLayeredPane {

    /**
     * Creates new form ChatLeft
     */
    public ChatLeft() {
        initComponents();
        
        msg.setBackground(new Color(242,242,242));
    }
    
    public void setUserProfile (String user) {
        msg.setUserProfile(user);
    }

    public void setAvatar(Icon image) {
        imageAva.setImage(image);
    }
    
    public void setMsg(String text) {
        if (text.equals("")) {
            msg.hideText();
        } else {
            msg.setMsg(text);
        }
        //msg.setMsg(text);
        //msg.setTime(new Date().toString().substring(11,20));
        //msg.sendMsgSuccess();
    }
    
    public void setImage(Icon... image) {
        msg.setImage(false, image);
    }
    
    public void setImage(String[] image) {
        msg.setImage(false, image);
    }
    
    public void setFile(String fileName, String fileSize) {
        msg.setFile(fileName, fileSize);
    }
    
    public void setTime() {
        msg.setTime();
    }
    
    public void setEmoji(Icon icon) {
        msg.hideText();
        msg.setEmoji(false, icon);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        imageAva = new Swing.ImageAvatar();
        msg = new Component.ChatItem();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        imageAva.setBorderSize(1);
        imageAva.setImage(new javax.swing.ImageIcon(getClass().getResource("/Icons/IconUser.png"))); // NOI18N

        jLayeredPane1.setLayer(imageAva, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addComponent(imageAva, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(imageAva, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        add(jLayeredPane1);
        add(msg);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Swing.ImageAvatar imageAva;
    private javax.swing.JLayeredPane jLayeredPane1;
    private Component.ChatItem msg;
    // End of variables declaration//GEN-END:variables


}
