package Component;

import Client.Send_File;
import java.awt.Color;
import java.util.Calendar;
import java.util.Date;
import javax.swing.Icon;

/**
 *
 * @author HOAI THU
 */
public class ChatRight extends javax.swing.JLayeredPane {

    /**
     * Creates new form ChatLeft
     */
    public ChatRight() {
        initComponents();
        
        msg.setBackground(new Color(255, 235, 248));
    }

    public void setMsg(String text) {
        if (text.equals("")) {
            msg.hideText();
        } else {
            msg.setMsg(text);
        }
        //msg.seenMsg();
    }
    
    public void setImage(Send_File fileSender) {
        msg.setImage(true, fileSender);
    }

    
    public void setImage(Icon... image) {
        msg.setImage(true, image);
    }
    
    public void setImage(String[] image) {
        msg.setImage(false, image);
    }
    
    public void setFile(String fileName, String fileSize) {
        msg.setFile(fileName, fileSize);
    }
    
    public void setEmoji(Icon icon) {
        msg.hideText();
        msg.setEmoji(true, icon);
    }
    
    public void setTime() {
        msg.setTime();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        msg = new Component.ChatItem();

        setLayer(msg, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(msg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(msg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Component.ChatItem msg;
    // End of variables declaration//GEN-END:variables

}
