package Component;

import Client.Send_File;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.FlowLayout;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.util.Date;
import javax.swing.BorderFactory;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JLayeredPane;
import javax.swing.JPanel;
import javax.swing.border.EmptyBorder;

/**
 *
 * @author HOAI THU
 */
public class ChatItem extends JPanel {

    private static JLabel lb;
    /**
     * Creates new form ItemChat
     */
    public ChatItem() {
        initComponents();
        msg.setEditable(false);
        msg.setBackground(new Color(0,0,0, 0));
        msg.setOpaque(false);
    }

    public void setUserProfile(String user) {
        JLayeredPane layer = new JLayeredPane();
        layer.setLayout(new FlowLayout(FlowLayout.LEFT, 0 ,0));
        layer.setBorder(new EmptyBorder(10,10,0,10));
        JButton cmd = new JButton(user);
        cmd.setBorder(null);
        cmd.setCursor(new Cursor(Cursor.HAND_CURSOR));
        cmd.setContentAreaFilled(false);
        cmd.setFocusable(false);
        cmd.setForeground(new Color(41, 193, 227));
        cmd.setFont(new Font("Cambria", 1, 13));
        msg.setBorder(BorderFactory.createEmptyBorder(5,10,10,10));
        layer.add(cmd);
        add(layer, 0);
    }
    
    public void setMsg(String text) {
        msg.setText(text);
        msg.setFont(new Font("Cambria", 0, 12));
    }
    
    public void setTime() {
        JLayeredPane layer = new JLayeredPane();
        layer.setLayout(new FlowLayout(FlowLayout.RIGHT, 0 ,0));
        layer.setBorder(new EmptyBorder(0,5,5,5));
        lb = new JLabel(new Date().toString().substring(11,16));
        lb.setForeground(new Color(36, 156, 56));
        lb.setHorizontalTextPosition(JLabel.LEFT);
        lb.setFont(new Font("Cambria", 0, 8));
        layer.add(lb);
        add(layer);
    }
    
     public void setEmoji(boolean right, Icon icon) {
        JLayeredPane layer = new JLayeredPane();
        layer.setLayout(new FlowLayout(right ? FlowLayout.RIGHT : FlowLayout.LEFT));
        layer.setBorder(new EmptyBorder(0, 5, 0, 5));
        layer.add(new JLabel(icon));
        add(layer);
        setBackground(null);
    }
    
    public void sendMsgSuccess() {
        if (lb != null) {
            lb.setIcon(new ImageIcon(getClass().getResource("/Icons/IconTick.png")));
        }
    }
    
    public void seenMsg() {
        if (lb != null) {
            lb.setIcon(new ImageIcon(getClass().getResource("/Icons/IconDoubleTick.png")));
        }
    }
    
    @Override
    protected void paintComponent(Graphics gp) {
        Graphics2D g = (Graphics2D) gp;
        g.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        g.setColor(getBackground());
        g.fillRoundRect(0, 0, getWidth(), getHeight(), 15, 15);
        super.paintComponent(gp);
    }
    
    public void setImage(boolean right, Send_File fileSender) {
        JLayeredPane layer = new JLayeredPane();
        layer.setLayout(new FlowLayout(right ? FlowLayout.RIGHT : FlowLayout.LEFT));
        layer.setBorder(new EmptyBorder(0, 5, 0, 5));
        ChatImage chatImage = new ChatImage(right);
        chatImage.addImage(fileSender);
        layer.add(chatImage);
        add(layer);

    }
    
    public void setImage(boolean right, Icon... image) {
        JLayeredPane layer = new JLayeredPane();
        layer.setLayout(new FlowLayout(right ? FlowLayout.RIGHT : FlowLayout.LEFT));
        ChatImage img = new ChatImage(right);
        img.addImage(image);
        layer.add(img);
        add(layer);
    }
    
    public void setImage(boolean right, String[] image) {
        JLayeredPane layer = new JLayeredPane();
        layer.setLayout(new FlowLayout(right ? FlowLayout.RIGHT : FlowLayout.LEFT));
        ChatImage img = new ChatImage(right);
        img.addImage(image);
        layer.add(img);
        add(layer);
    }
    
    public void setFile(String fileName, String fileSize) {
        JLayeredPane layer = new JLayeredPane();
        layer.setLayout(new FlowLayout(FlowLayout.LEFT));
        ChatFile cF = new ChatFile();
        cF.setFile(fileName, fileSize);
        layer.add(cF);
        add(layer);
    }
    
    public void hideText() {
        msg.setVisible(false);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        msg = new Swing.JIMSendTextPane();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.PAGE_AXIS));

        msg.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 5, 10));
        msg.setSelectionColor(new java.awt.Color(64, 135, 191));
        add(msg);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Swing.JIMSendTextPane msg;
    // End of variables declaration//GEN-END:variables

}
