package Component;

import Client.User_Account;
import Events.PublicEvent;
import java.awt.Color;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

public class ItemUser extends javax.swing.JPanel {

    public User_Account getUser() {
        return user;
    }
    
    private boolean mouseOver;
    public final User_Account user;
    
    public ItemUser(User_Account user) {
        this.user = user;
        initComponents();
        lbName.setText(user.getUsername());
        activeStatus.setActive(user.isStatus());
        init();
    }
    
    public void updateStatus() {
        activeStatus.setActive(user.isStatus());
    }

    public void init() {
        addMouseListener(new MouseAdapter() {
            @Override
            public void mouseEntered(MouseEvent mE) {
                ItemUser.setBackground(new Color(252, 235, 251));
                mouseOver = true;
            }
            
            @Override
            public void mouseExited(MouseEvent mE) {
                ItemUser.setBackground(new Color(255,255,255));
                mouseOver = false;
            }
            
            @Override
            public void mouseReleased(MouseEvent me) {
                if (mouseOver) {
                    PublicEvent.getInstance().getMainEvent().selectUser(user);
                }
            }
        });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ItemUser = new javax.swing.JPanel();
        imageAvatar2 = new Swing.ImageAvatar();
        lbStatus = new javax.swing.JLabel();
        lbName = new javax.swing.JLabel();
        activeStatus = new Swing.ActiveStatus();

        ItemUser.setBackground(new java.awt.Color(255, 255, 255));
        ItemUser.setLayout(null);

        imageAvatar2.setBorderSize(1);
        imageAvatar2.setImage(new javax.swing.ImageIcon(getClass().getResource("/Icons/IconUser.png"))); // NOI18N
        ItemUser.add(imageAvatar2);
        imageAvatar2.setBounds(10, 10, 30, 30);

        lbStatus.setFont(new java.awt.Font("Cambria", 2, 10)); // NOI18N
        lbStatus.setForeground(new java.awt.Color(102, 102, 102));
        lbStatus.setText("Name");
        ItemUser.add(lbStatus);
        lbStatus.setBounds(50, 23, 40, 20);

        lbName.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        lbName.setText("Name");
        ItemUser.add(lbName);
        lbName.setBounds(50, 0, 80, 20);

        activeStatus.setActive(true);
        ItemUser.add(activeStatus);
        activeStatus.setBounds(90, 30, 8, 10);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(ItemUser, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ItemUser, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ItemUser;
    private Swing.ActiveStatus activeStatus;
    private Swing.ImageAvatar imageAvatar2;
    private javax.swing.JLabel lbName;
    private javax.swing.JLabel lbStatus;
    // End of variables declaration//GEN-END:variables
}
