package Form;

import Client.User_Account;
import net.miginfocom.swing.MigLayout;

/**
 *
 * @author HOAI THU
 */
public class Home extends javax.swing.JLayeredPane {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }
    
    public void setUser(User_Account user) {
        chat.setUser(user);
        chat.setVisible(true);
    }

    public void updateUser(User_Account user) {
        chat.updateUser(user);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Body = new javax.swing.JLayeredPane();
        menuLeft = new Form.MenuLeft();
        chat = new Form.Chat();

        Body.add(menuLeft);
        menuLeft.setBounds(10, 40, 150, 330);
        Body.add(chat);
        chat.setBounds(170, 30, 430, 340);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Body, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Body, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane Body;
    private Form.Chat chat;
    private Form.MenuLeft menuLeft;
    // End of variables declaration//GEN-END:variables
}
