package Form;

import Component.ItemUser;
import Events.MenuLeftEvent;
import Events.PublicEvent;
import Client.Service;
import Client.User_Account;
import Swing.ComponentResizer;
import Swing.ScrollBar;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import net.miginfocom.swing.MigLayout;

/**
 *
 * @author HOAI THU
 */
public class MenuLeft extends javax.swing.JPanel {

    private List<User_Account> userAccount;
    
    public MenuLeft() {
        initComponents();
        init();
    }

    private void init() {
        jScrollPane1.setVerticalScrollBar(new ScrollBar());
        MenuList.setLayout(new MigLayout("fillx", "2[]2", "2[]2"));
       
        userAccount = new ArrayList<>();
       
        PublicEvent.getInstance().addMenuLeftEvent(new MenuLeftEvent() {
            @Override
            public void newUser(List<User_Account> users) {
                for (User_Account d : users) {
                    userAccount.add(d);
                    MenuList.add(new ItemUser(d), "wrap");
                    refreshMenuList();
                }
            }

            @Override
            public void userConnect(int userID) {
                for (User_Account u : userAccount) {
                    if (u.getID() == userID) {
                        u.setStatus(true);
                        break;
                    }
                }
                if (MenuMess.isSelected()) {
                    for (Component com : MenuList.getComponents()) {
                        ItemUser item = (ItemUser) com;
                        if (item.getUser().getID() == userID) {
                            item.updateStatus();
                            break;
                        }
                    }
                }
            }

            @Override
            public void userDisconnect(int userID) {
                for (User_Account u : userAccount) {
                    if (u.getID() == userID) {
                        u.setStatus(false);
                        break;
                    }
                }
                if (MenuMess.isSelected()) {
                    for (Component com : MenuList.getComponents()) {
                        ItemUser item = (ItemUser) com;
                        if (item.getUser().getID() == userID) {
                            item.updateStatus();
                            break;
                        }
                    }
                }
            }
        });
        
        showMess();
    }
    
    private void showMess() {
        MenuList.removeAll();
        for (User_Account d : userAccount) {
            MenuList.add(new ItemUser(null), "wrap");
        }
        refreshMenuList();
    }
    
    private void showGroup() {
        MenuList.removeAll();
        for (int i = 0; i < 10; i++) {
            MenuList.add(new ItemUser(null), "wrap");
        }
        refreshMenuList();
    }
    
    private void showBox() {
        MenuList.removeAll();
        for (int i = 0; i < 10; i++) {
            MenuList.add(new ItemUser(null), "wrap");
        }
        refreshMenuList();
    }
    
    private void refreshMenuList() {
        MenuList.repaint();
        MenuList.revalidate();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MenuLeft = new javax.swing.JPanel();
        MenuButton = new javax.swing.JLayeredPane();
        MenuMess = new javax.swing.JButton();
        MenuGroup = new javax.swing.JButton();
        MenuBox = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        MenuList = new javax.swing.JLayeredPane();

        MenuLeft.setBackground(new java.awt.Color(255, 255, 255));

        MenuButton.setOpaque(true);

        MenuMess.setBackground(new java.awt.Color(255, 255, 255));
        MenuMess.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/IconMess.png"))); // NOI18N
        MenuMess.setSelected(true);
        MenuMess.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/IconMessSelected.png"))); // NOI18N
        MenuMess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuMessActionPerformed(evt);
            }
        });

        MenuGroup.setBackground(new java.awt.Color(255, 255, 255));
        MenuGroup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/IconGroup.png"))); // NOI18N
        MenuGroup.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/IconGroupSelected.png"))); // NOI18N
        MenuGroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuGroupActionPerformed(evt);
            }
        });

        MenuBox.setBackground(new java.awt.Color(255, 255, 255));
        MenuBox.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/IconBox.png"))); // NOI18N
        MenuBox.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/IconBoxSelected.png"))); // NOI18N
        MenuBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuBoxActionPerformed(evt);
            }
        });

        MenuButton.setLayer(MenuMess, javax.swing.JLayeredPane.DEFAULT_LAYER);
        MenuButton.setLayer(MenuGroup, javax.swing.JLayeredPane.DEFAULT_LAYER);
        MenuButton.setLayer(MenuBox, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout MenuButtonLayout = new javax.swing.GroupLayout(MenuButton);
        MenuButton.setLayout(MenuButtonLayout);
        MenuButtonLayout.setHorizontalGroup(
            MenuButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuButtonLayout.createSequentialGroup()
                .addComponent(MenuMess, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(MenuGroup, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(MenuBox, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
        );
        MenuButtonLayout.setVerticalGroup(
            MenuButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MenuMess, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(MenuGroup, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(MenuBox, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setToolTipText("");

        MenuList.setOpaque(true);

        javax.swing.GroupLayout MenuListLayout = new javax.swing.GroupLayout(MenuList);
        MenuList.setLayout(MenuListLayout);
        MenuListLayout.setHorizontalGroup(
            MenuListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );
        MenuListLayout.setVerticalGroup(
            MenuListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 291, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(MenuList);

        javax.swing.GroupLayout MenuLeftLayout = new javax.swing.GroupLayout(MenuLeft);
        MenuLeft.setLayout(MenuLeftLayout);
        MenuLeftLayout.setHorizontalGroup(
            MenuLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MenuButton)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        MenuLeftLayout.setVerticalGroup(
            MenuLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLeftLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(MenuButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(MenuLeft, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 330, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(MenuLeft, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void MenuMessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuMessActionPerformed
        // TODO add your handling code here:
        if(!MenuMess.isSelected()) {
            MenuMess.setSelected(true);
            MenuGroup.setSelected(false);
            MenuBox.setSelected(false);
            showMess();
        }
    }//GEN-LAST:event_MenuMessActionPerformed

    private void MenuGroupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuGroupActionPerformed
        // TODO add your handling code here:
        if(!MenuGroup.isSelected()) {
            MenuMess.setSelected(false);
            MenuGroup.setSelected(true);
            MenuBox.setSelected(false);
            showGroup();
        }
    }//GEN-LAST:event_MenuGroupActionPerformed

    private void MenuBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuBoxActionPerformed
        // TODO add your handling code here:
        if(!MenuBox.isSelected()) {
            MenuMess.setSelected(false);
            MenuGroup.setSelected(false);
            MenuBox.setSelected(true);
            showBox();
        }
    }//GEN-LAST:event_MenuBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton MenuBox;
    private javax.swing.JLayeredPane MenuButton;
    private javax.swing.JButton MenuGroup;
    private javax.swing.JPanel MenuLeft;
    private javax.swing.JLayeredPane MenuList;
    private javax.swing.JButton MenuMess;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
